### ISSUE TITLE
Great Start, but found some issues

### ISSUE THREAD

**Issue by LordUnderscore** [ofdl/ofdl#3]
Hi, 

Looks great, but when I started using this I found a few rough edges:

1. The limits aren't very clear, e.g. `ofdl scrape subs` says it only scrapes 50 users, so does that mean I've to run it multiple times to scrape everyone?
2. Similar with downloading, why limit to 1000, do I run again for more?
3. It would be nice to pick which subs I want to scrape. I'm subscribed to a lot of free ones, but it's the paid subs I'm most interested in downloading.
5. Tbh, I had never heard of aria2, but I have an unraid server, so I set up aria as it looked like a great idea to split the responsibility of scraping from downloading. One issue I ran into though was the paths sent to aria2 used backslashes `\` so it complained about not being able to create the directory. I'm assuming this was because I'm running `ofdl` on Windows and aria2 on Linux?

I'm more it a Python guy, otherwise I'd try dive in and fix it myself.

**Comment by ofdl** [comment]
Thanks for the feedback!

1. v0.1.5 improves subscription scraping, utilizing the API's `limit` and `offset` fields more intelligently to ensure that all of your active subscriptions are scraped.
2. v0.1.5 addresses this for you by allowing you to specify the batch size with `ofdl config set downloads.batch-size 1000`. It also improves the in-app documentation by clarifying the answer to your question. Yes, run the command again to download another batch.
3. v0.1.4 introduces a simple subscription manager. Run `ofdl subs` to get a list of subscriptions, and enable/disable them with the spacebar.
4. Glad you like the idea of Aria2. I also run it on my NAS. I understand the issue you're facing with unix and windows path formats. I'll have to come back to this, as I'm not entirely sure how to address it. Since Aria2 runs on both linux and windows, and should be decoupled with the platform on which you're running `ofdl`, it'll probably require some additional configuration. Stay tuned.

**Comment by ofdl** [comment]
v0.1.6 addresses your issue by using unix-style paths by default (ignoring the system's preference) while generating paths for Aria2. It also introduces support for Aria2 running on Windows, which is unrelated to your use-case.

**Comment by LordUnderscore** [comment]
The v0.1.5 binaries didn't work for me out of the box, something to do with missing some sqlite dependency; I had to compile it myself, and then it worked fine.
